# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cefdb8e4da75e63419f9ddd6ff0d60607ce95f5733881251f3b39c4197dfc5a8c1573e8f9d1d7c58ad65e59e5c0658af7fef08a6a9114d0a12702314cb93773

test:
  secret_key_base: f622f1e1c438c2c42a54d0d261cb9d51e342bdaf0c44ef4c5f7b6eae17466cf87e395f9aa50be342874b806f058355bbe942cc0e63042a084ce5692912e82bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
